### ISSUE TITLE
Support for Servant 0.17 and up

### ISSUE THREAD

**Issue by ollef** [folq/servant-to-elm#12]
Servant 0.17 has [changed the way `NoContent` works](https://github.com/haskell-servant/servant/blob/master/servant/CHANGELOG.md#017), which will probably require some changes on our end.

**Comment by seagreen** [comment]
Is this still an issue? I've got a branch of my app working with `servant-0.18.2` and it's compiling fine.

EDIT: That is with `servant-to-elm-0.4.2.0` from Hackage.

**Comment by ollef** [comment]
Sounds like it's not, cheers!

**Comment by seagreen** [comment]
Would you be willing to raise/remove the servant upper bound and do a new release?

**Comment by ollef** [comment]
Would you like to do this yourself? I have added you as a maintainer here on Github and on Hackage.

**Comment by seagreen** [comment]
Can do. I was wrong about this taking no changes btw, PR on the way.

**Comment by seagreen** [comment]
https://github.com/folq/servant-to-elm/pull/14

Figured out why I thought it wouldn't take any changes: the library compiles fine with later versions of servant, however use of `PostNoContent` doesn't work without changes.
