### ISSUE TITLE
Support `tracker` to be able to cancel old requests

### ISSUE THREAD

**Issue by hanshenrik** [folq/servant-to-elm#15]
Sometimes we need to discard old requests. Our specific case is search, where the user changes search parameters quickly, and search request A takes longer than search request B to finish. In those cases, we end up using the last arrived response from the API, i.e. search request A. Not good.

The Http package supports [cancelling requests by using a tracker](https://package.elm-lang.org/packages/elm/http/latest/Http#cancel). It would be nice to expose this feature here as well.

To avoid this change forcing the client to always deal with this, since a tracker is not needed in most cases, we should try to add it in a way that is opt in.

Relevant code: https://github.com/folq/servant-to-elm/blob/2b42e522c87aa96e4de84b877115991ea5a85848/src/Servant/To/Elm.hs#L135

**Comment by hanshenrik** [comment]
We solved this by adding a sequence number to the `Msg` and keeping the sequence number of the newest request in the model. This way we can ignore results from the old requests.

```
GotResultMsg sequenceNumber result ->
  if sequenceNumber < model.sequenceNumber then
    -- Ignore results from old requests
    ( model, Cmd.none )

  else
    ...
```

But I think supporting `tracker` and possibly other things like `timeout` will still be an improvement to `servant-to-elm`, so I'll keep the issue open and see if I (or some one else) gets the time to fix it at some point in the future 🤞

**Comment by seagreen** [comment]
Check out the new [elmEndpointRequestInfo](https://github.com/folq/servant-to-elm/blob/2b42e522c87aa96e4de84b877115991ea5a85848/src/Servant/To/Elm.hs#L147) function, does it do what you want?

**Comment by seagreen** [comment]
(Relatively new that is, since Dec 2020)

**Comment by hanshenrik** [comment]
Yes, of course, how did I miss that 🙄 Thanks!
