### ISSUE TITLE
How to handle non Elm endpoints

### ISSUE THREAD

**Issue by rl-king** [folq/servant-to-elm#3]
Any tips on how to "select" the endpoints for which to generate elm code?

I'm currently using this definition

```hs
data API route = API
  { aGetNote :: route :- "data" :> "note" :> Capture "id" Int32 :> Get '[JSON] Note,
    aPostNote :: route :- "data" :> "note" :> ReqBody '[JSON] NewNote :> Post '[JSON] Note,
    aRaw :: route :- Raw
  }
  deriving (Generic)

defs =
  fmap (Servant.To.Elm.elmEndpointDefinition "Config.urlBase" ["Request"]) $
    Servant.To.Elm.elmEndpoints @(ToServantApi API)
```

Which gives me the following error: `No instance for (Servant.To.Elm.HasElmEndpoints Raw)`

As a workaround I duplicate the routes I need but there might some nicer way to go about this.

**Comment by ollef** [comment]
We sort of do it the way you suggest, but to avoid duplication we put all endpoints we want to generate code for in one type and then nest that type inside a bigger type that contains some additional endpoints.

**Comment by rl-king** [comment]
Yeah I thought of that, it's a bit nicer indeed, I'll do that for now. It does feel a bit weird how this affects the way you have to structure your code although I have little reason to _not_ split it up :)

Thanks!

**Comment by rl-king** [comment]
For completeness an example of what I ended up with:

```hs
data Api route = Api
  { aNotesApi :: route :- ToServantApi NoteApi,
    aRaw :: route :- Raw
  }
  deriving (Generic)

data NoteApi route = NoteApi
  { naGetNote :: route :- "data" :> "note" :> Capture "id" Int32 :> Get '[JSON] Note,
    naPostNote :: route :- "data" :> "note" :> ReqBody '[JSON] NewNote :> Post '[JSON] Note
  }
  deriving (Generic)
```
