### ISSUE TITLE
Elm 0.19 support?

### ISSUE THREAD

**Issue by Clindbergh** [folq/servant-to-elm#8]
It appears that the code is not Elm 0.19 compatible.

- The code contains an import of `Signal` - I think this is a thing of Elm's past?
- An `elm.json` file is missing, imports have to be added manually
- `elm-make` in the makefile is now `elm make` (assuming this is using the default elm compiler)

_This issue was intended for the [example repo](https://github.com/mattjbray/servant-elm-example-app), it may be [transferred](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/transferring-an-issue-to-another-repository)_

**Comment by ollef** [comment]
`servant-to-elm` is not the same as `servant-elm`.

`servant-to-elm` is compatible with Elm 0.19.
