### ISSUE TITLE
Alternative to elmEndpointDefinition that returns a record instead of `Cmd`

### ISSUE THREAD

**Issue by seagreen** [folq/servant-to-elm#9]
Using `elmEndpointDefinition` to generate Elm functions which return `Cmd` is definitely convenient.

However, there are two situations this doesn't cover. The first is when you wish to use the `timeout` or `tracker` options to [Http.request](https://package.elm-lang.org/packages/elm/http/latest/Http#request). The second is when you wish to use an alternative to `request` entirely, like [Http.task](https://package.elm-lang.org/packages/elm/http/latest/Http#task) or [Http.riskyRequest](https://package.elm-lang.org/packages/elm/http/latest/Http#riskyRequest).

Would you be interested in a new helper function in the library with the same type signature as `elmEndpointDefinition`, but which generates an Elm function that returns:
```elm
{ method : String
, headers : List Header
, url : String
, body : Body
, expect : Expect msg
, timeout : Maybe Float -- actually this could be left off
, tracker : Maybe String -- same with this
}
```
instead of:
```elm
Cmd
    (Result
        ( Http.Error
        , Maybe
            { metadata : Http.Metadata
            , body : String
             }
        )
        msg
    )
```

**Comment by ollef** [comment]
This sounds like a good idea that'd be useful!

**Comment by ollef** [comment]
Fixed by @seagreen! :heart:
